# Generated by Django 3.1.1 on 2020-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choiceApp', '0002_auto_20201016_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/photos/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatar/'),
        ),
    ]
