# Generated by Django 3.1.1 on 2020-10-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choiceApp', '0003_auto_20201017_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ManyToManyField(related_name='photos', to='choiceApp.Photo'),
        ),
    ]
